services:
  db:
    container_name: pg_digital_cash_vault
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root!23456
      POSTGRES_DB: dcv_dev
    ports:
      - "5432:5432"
